export default {
	FETCH_TRANSFORMER_ALLEGIANCE: 'FETCH_TRANSFORMER_ALLEGIANCE',
	UPDATE_TRANSFORMER_ALLEGIANCE: 'UPDATE_TRANSFORMER_ALLEGIANCE',
	RECEIVE_NEW_TRANSFORMER_DATA: 'RECEIVE_NEW_TRANSFORMER_DATA',
};
